2020-05-11 10:01:42,426 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_run.py[line:64] - ERROR: File is not a zip file
2020-05-11 10:01:47,583 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_run.py[line:64] - ERROR: File is not a zip file
2020-05-11 10:06:17,381 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_run.py[line:113] - ERROR: Wrong type of training
2020-05-11 10:06:17,381 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_run.py[line:64] - ERROR: 'bool' object is not subscriptable
2020-05-11 10:06:24,496 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_run.py[line:113] - ERROR: Wrong type of training
2020-05-11 10:06:24,496 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_run.py[line:64] - ERROR: 'bool' object is not subscriptable
2020-05-11 10:06:31,966 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_run.py[line:113] - ERROR: Wrong type of training
2020-05-11 10:06:31,966 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_run.py[line:64] - ERROR: 'bool' object is not subscriptable
2020-05-11 10:10:10,549 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_database_operate.py[line:130] - ERROR: data insert error (pymysql.err.IntegrityError) (1062, "Duplicate entry '2-V10' for key 'modelmanagement_datasett_training_model_id_model__95f493e0_uniq'") [SQL: 'INSERT INTO modelmanagement_datasettrainingmodel (training_time, accuracy_rate, model_version, model_fileaddr, dataset_list, training_model_id) VALUES (%(training_time)s, %(accuracy_rate)s, %(model_version)s, %(model_fileaddr)s, %(dataset_list)s, %(training_model_id)s)'] [parameters: {'training_time': '2020-05-11 10:10:06', 'accuracy_rate': 90.0, 'model_version': 'V10', 'model_fileaddr': '/ModelFiles/进气阀测试模型_V10.h5', 'dataset_list': '1, 2, 3', 'training_model_id': 2}]
2020-05-11 10:10:10,555 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_run.py[line:120] - ERROR: init opt result save error 1589162705.2158005
2020-05-11 10:10:10,565 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_run.py[line:65] - ERROR: 'train_model_id'
2020-05-11 10:10:18,456 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_database_operate.py[line:130] - ERROR: data insert error (pymysql.err.IntegrityError) (1062, "Duplicate entry '2-V10' for key 'modelmanagement_datasett_training_model_id_model__95f493e0_uniq'") [SQL: 'INSERT INTO modelmanagement_datasettrainingmodel (training_time, accuracy_rate, model_version, model_fileaddr, dataset_list, training_model_id) VALUES (%(training_time)s, %(accuracy_rate)s, %(model_version)s, %(model_fileaddr)s, %(dataset_list)s, %(training_model_id)s)'] [parameters: {'training_time': '2020-05-11 10:10:14', 'accuracy_rate': 90.0, 'model_version': 'V10', 'model_fileaddr': '/ModelFiles/进气阀测试模型_V10_V10.h5', 'dataset_list': '1, 2, 3', 'training_model_id': 2}]
2020-05-11 10:10:18,468 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_run.py[line:120] - ERROR: init opt result save error 1589162705.2158005
2020-05-11 10:10:18,469 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_run.py[line:65] - ERROR: 'train_model_id'
2020-05-11 10:13:26,575 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_database_operate.py[line:130] - ERROR: data insert error (pymysql.err.IntegrityError) (1062, "Duplicate entry '2-V10' for key 'modelmanagement_datasett_training_model_id_model__95f493e0_uniq'") [SQL: 'INSERT INTO modelmanagement_datasettrainingmodel (training_time, accuracy_rate, model_version, model_fileaddr, dataset_list, training_model_id) VALUES (%(training_time)s, %(accuracy_rate)s, %(model_version)s, %(model_fileaddr)s, %(dataset_list)s, %(training_model_id)s)'] [parameters: {'training_time': '2020-05-11 10:12:21', 'accuracy_rate': 90.0, 'model_version': 'V10', 'model_fileaddr': '/ModelFiles/进气阀测试模型_V10_V10_V10.h5', 'dataset_list': '1, 2, 3', 'training_model_id': 2}]
2020-05-11 10:13:26,585 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_run.py[line:120] - ERROR: init opt result save error 1589162705.2158005
2020-05-11 10:13:26,586 - e:\桌面\app\work_project\Car_Engine\code\CarEngine\codeV5\mid_run.py[line:65] - ERROR: 'train_model_id'
2020-05-18 15:15:37,459 - /home/briup/Charisse/ModelingSystem_Mid/mid_run.py[line:67] - ERROR: unexpected EOF while parsing (<unknown>, line 0)
2020-05-18 15:15:37,470 - /home/briup/Charisse/ModelingSystem_Mid/mid_run.py[line:67] - ERROR: unexpected EOF while parsing (<unknown>, line 0)
2020-05-18 15:15:43,881 - /home/briup/Charisse/ModelingSystem_Mid/mid_run.py[line:67] - ERROR: unexpected EOF while parsing (<unknown>, line 0)
2020-05-18 15:15:43,890 - /home/briup/Charisse/ModelingSystem_Mid/mid_run.py[line:67] - ERROR: unexpected EOF while parsing (<unknown>, line 0)
2020-05-18 15:15:58,419 - /home/briup/Charisse/ModelingSystem_Mid/mid_run.py[line:67] - ERROR: unexpected EOF while parsing (<unknown>, line 0)
2020-05-18 15:15:58,425 - /home/briup/Charisse/ModelingSystem_Mid/mid_run.py[line:67] - ERROR: unexpected EOF while parsing (<unknown>, line 0)
